### ISSUE TITLE
Do we still need this repo?

### ISSUE THREAD

**Issue by jiahao** [JuliaAttic/readline#1]

**Comment by Keno** [comment]
No, not sure if there's any harm in keeping it though.

**Comment by ViralBShah** [comment]
Can we move it out of JuliaLang? 

Cc @tkelman

**Comment by tkelman** [comment]
Some very old versions of Julia likely had the url hardcoded. I'd want to avoid breaking them for archival purposes, and this isn't hurting much of anything other than clutter.
